version: 2.1

ubuntu_image: &ubuntu_image
  ubuntu:18.04
install-sudo: &install-sudo |
  apt-get update
  apt-get install -y sudo curl

executors:
  ubuntu-docker:
    docker:
      - image: *ubuntu_image

orbs:
  discord-orb: tkyshm/discord-orb@0.0.8

jobs:
  success:
    executor: ubuntu-docker
    steps:
      - run:
          command: *install-sudo
      - discord-orb/notify

  fail:
    executor: ubuntu-docker
    steps:
      - run: 
          command: exit 1
      - discord-orb/notify

workflows:
  main:
    jobs:
      - success
      - fail
